### ISSUE TITLE
群聊中setu功能报错

### ISSUE THREAD

**Issue by G41mywaifu** [Chendihe4975/nonebot2-plugins#1]
![图片](https://user-images.githubusercontent.com/81564864/133173048-07076b2e-b200-4139-90eb-f84ab45eafc8.png)
私聊使用没有问题  群聊中会出现这样的报错
自动缓存时日志中显示了下载成功 但是image文件夹中没有图片 
config是这样
![图片](https://user-images.githubusercontent.com/81564864/133176794-81b4d470-1bb9-464d-b839-f8dedf9838d7.png)

**Comment by DiheChen** [comment]
合并转发发送者字段是从nonebot2的配置文件.env.{environment}随机选择nickname, 请为你的机器人设定nickname。
稍后测试自动缓存功能的问题, 稍等。
